#!/usr/bin/env python3
"""
Sync llms.txt and llms-full.txt from Mikrotik documentation.

Fetches fresh copies from https://manual.mikrotik.com/llms.txt and
https://manual.mikrotik.com/llms-full.txt, with diff check and version bump logic.

Usage:
  python3 scripts/sync_llms.py [--check] [--force]

Options:
  --check  Dry-run: fetch and show diff stats without writing files.
  --force  Force overwrite even if content unchanged.

Behavior:
  - Fetches both files via urllib with timeout and retries.
  - Computes SHA-256 hash and compares to local files.
  - Extracts RouterOS version hints from llms-full.txt (header, for logging;
    highest feature-gate mention, recorded in the provenance manifest).
  - If changed, overwrites local files and prints version diff.
  - Maintains data/upstream-docs.toml, a provenance manifest recording which
    upstream bytes were synced (per-file SHA256, RouterOS version hint, UTC
    timestamp). Written only on real runs: rewritten whenever anything changed
    (--force counts), bootstrapped once when missing, left untouched otherwise
    so git-diff gates see zero churn. Never written in --check mode.
  - Exits 0 on success, 1 on fetch failure, 2 if --check detects pending changes.
"""

import argparse
import hashlib
import os
import re
import sys
import tempfile
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

BASE_URL = "https://manual.mikrotik.com"
FILES = {
    "llms.txt": f"{BASE_URL}/llms.txt",
    "llms-full.txt": f"{BASE_URL}/llms-full.txt",
}
# Stable manifest identity per source (index before full, deterministic order).
SOURCE_NAMES = {
    "llms.txt": "index",
    "llms-full.txt": "full",
}
MANIFEST_RELPATH = Path("data") / "upstream-docs.toml"
MANIFEST_HEADER = (
    "# Upstream RouterOS documentation snapshot provenance.\n"
    "# Auto-generated by scripts/sync_llms.py — do not hand-edit.\n"
    "# Regenerate with: make sync   (or python3 scripts/sync_llms.py)\n"
)

TIMEOUT = 30  # seconds
RETRIES = 3


def fetch_url(url: str) -> bytes:
    """Fetch URL with retries, timeout, and proper headers."""
    last_exc = None
    for attempt in range(1, RETRIES + 1):
        try:
            req = urllib.request.Request(
                url,
                headers={
                    "User-Agent": "mikrotik-zed sync_llms.py/1.0",
                    "Accept": "text/plain, text/markdown, */*",
                },
            )
            with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
                if resp.status != 200:
                    raise urllib.error.HTTPError(url, resp.status, f"HTTP {resp.status}", resp.headers, None)
                return resp.read()
        except Exception as e:
            last_exc = e
            print(f"Attempt {attempt}/{RETRIES} failed for {url}: {e}", file=sys.stderr)
            if attempt < RETRIES:
                time.sleep(2**attempt)
                continue
    raise last_exc  # type: ignore[misc]


def sha256(data: bytes) -> str:
    h = hashlib.sha256()
    h.update(data)
    return h.hexdigest()


def sha256_file(path: Path) -> str | None:
    if not path.exists():
        return None
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def utc_now_iso() -> str:
    """Current UTC time as ISO-8601 with Z suffix (manifest timestamp format)."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def build_manifest_text(routeros_version: str, synced_at: str, sources: list[dict]) -> str:
    """Render the provenance manifest as TOML text.

    Pure helper (no network, no filesystem): identical inputs always produce
    identical bytes, keeping the committed baseline diff-stable. Values come
    from repo-controlled constants plus lowercase hex hashes, so no TOML
    escaping is needed — asserted defensively anyway.

    sources: ordered dicts with keys name, path, url, sha256.
    """
    for src in sources:
        for value in src.values():
            assert '"' not in value and "\\" not in value and "\n" not in value, f"unescapable manifest value: {value!r}"
    lines = [
        *MANIFEST_HEADER.rstrip("\n").split("\n"),
        "schema = 1",
        f'routeros_version = "{routeros_version}"',
        f'synced_at_utc = "{synced_at}"',
    ]
    for src in sources:
        name = src["name"]
        path = src["path"]
        url = src["url"]
        sha = src["sha256"]
        lines += [
            "",
            "[[sources]]",
            f'name = "{name}"',
            f'path = "{path}"',
            f'url = "{url}"',
            f'sha256 = "{sha}"',
        ]
    return "\n".join(lines) + "\n"


def write_manifest(path: Path, text: str) -> None:
    """Write the manifest atomically-ish: temp file in the target dir, then rename."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), prefix=path.name + ".", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as tmp:
            tmp.write(text)
            tmp.flush()
            os.fsync(tmp.fileno())
        os.replace(tmp_name, path)
    except BaseException:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


def extract_version(text: str) -> str:
    """Extract RouterOS version hint from text (first 8 KiB)."""
    head = text[:8192]
    m = re.search(r"RouterOS\s+v?(\d+\.\d+(?:\.\d+)?)", head, re.IGNORECASE)
    if m:
        return m.group(1)
    m = re.search(r"\b7\.\d+(?:\.\d+)?\b", head)
    if m:
        return m.group(0)
    return "unknown"


# Feature-gate mentions like "available since RouterOS v7.14" / "from RouterOS
# version 7.23". Full-word prefix only ("ROS ..." would false-positive on IPs),
# and no trailing word char, so pre-release tags like "7.24beta1" don't count
# as stable "7.24".
VERSION_MENTION_RE = re.compile(r"\bRouterOS\s+(?:version\s+)?v?(\d+\.\d+(?:\.\d+)?)(?!\w)", re.IGNORECASE)


def full_version_hint(text: str) -> str:
    """Best-effort RouterOS currency hint for the provenance manifest.

    The upstream docs carry no explicit header version, so derive one: the
    highest RouterOS feature-gate mention in the whole corpus approximates
    which RouterOS era these bytes describe. Deterministic given the bytes;
    "" when the text contains no usable mention.
    """
    best: tuple[int, ...] | None = None
    for m in VERSION_MENTION_RE.finditer(text):
        parts = tuple(int(p) for p in m.group(1).split("."))
        if best is None or parts > best:
            best = parts
    return ".".join(str(p) for p in best) if best else ""


def main(argv: list[str] | None = None, *, project_root: Path | None = None, fetch=None) -> int:
    parser = argparse.ArgumentParser(description="Sync llms.txt and llms-full.txt from manual.mikrotik.com")
    parser.add_argument("--check", action="store_true", help="Dry-run diff check without writing")
    parser.add_argument("--force", action="store_true", help="Force overwrite even if unchanged")
    args = parser.parse_args(argv)

    script_dir = Path(__file__).parent
    root = project_root if project_root is not None else (script_dir.parent if script_dir.name == "scripts" else script_dir)
    do_fetch = fetch_url if fetch is None else fetch

    overall_changed = False
    has_error = False
    # Staged writes for atomic two-file transaction (both held in memory until both fetches succeed).
    pending_writes: list[tuple[Path, bytes]] = []
    # Provenance record per successfully fetched file, in FILES order (index first).
    fetched: list[dict] = []
    # RouterOS version hint from llms-full.txt ("" when unknown).
    full_version = ""

    for filename, url in FILES.items():
        local_path = root / filename
        print(f"Fetching {url} ...")
        try:
            data = do_fetch(url)
        except Exception as e:
            print(f"ERROR: failed to fetch {url}: {e}", file=sys.stderr)
            has_error = True
            continue

        remote_hash = sha256(data)
        local_hash = sha256_file(local_path)
        remote_text = data.decode("utf-8", errors="ignore")
        remote_version = extract_version(remote_text)

        fetched.append(
            {
                "name": SOURCE_NAMES.get(filename, filename),
                "path": filename,
                "url": url,
                "sha256": remote_hash,
            }
        )
        if filename == "llms-full.txt":
            # Manifest hint: highest feature-gate mention in the corpus ("" if none).
            full_version = full_version_hint(remote_text)

        if local_hash is not None:
            local_version = extract_version(local_path.read_text(encoding="utf-8", errors="ignore"))
        else:
            local_version = "missing"

        if local_hash == remote_hash and not args.force:
            print(f"  {filename}: unchanged (hash {remote_hash[:16]}, version {remote_version})")
            continue

        # Diff stats
        if local_path.exists():
            local_lines = local_path.read_text(encoding="utf-8", errors="ignore").splitlines()
            remote_lines = remote_text.splitlines()
            added = len(remote_lines) - len(local_lines)
            print(f"  {filename}: changed (local {local_hash[:16] if local_hash else 'missing'} -> remote {remote_hash[:16]})")
            print(f"    version: {local_version} -> {remote_version}")
            print(f"    lines: {len(local_lines)} -> {len(remote_lines)} ({'+' if added >=0 else ''}{added})")
            # Simple diff bump hint: count headings
            local_headings = sum(1 for l in local_lines if l.startswith("## "))
            remote_headings = sum(1 for l in remote_lines if l.startswith("## "))
            print(f"    headings (##): {local_headings} -> {remote_headings} ({remote_headings - local_headings:+d})")
        else:
            print(f"  {filename}: new file (remote hash {remote_hash[:16]}, version {remote_version})")

        overall_changed = True

        if args.check:
            print(f"  {filename}: --check mode, not writing")
            continue

        # Stage for atomic flush after both fetches (mixed-generation guard).
        pending_writes.append((local_path, data))
        print(f"  {filename}: staged {len(data)} bytes (will write after both fetches)")

    # ── Atomic flush of staged upstream files ─────────
    if args.check:
        if pending_writes:
            print(f"staged {len(pending_writes)} file(s) not written (--check)")
    elif has_error:
        if pending_writes:
            print(
                f"discarding {len(pending_writes)} staged file(s) due to fetch error (atomic guard)",
                file=sys.stderr,
            )
            pending_writes.clear()
    elif pending_writes:
        for path, data in pending_writes:
            try:
                path.write_bytes(data)
                print(f"  {path.name}: wrote {len(data)} bytes")
            except Exception as e:
                print(f"ERROR: failed to write {path}: {e}", file=sys.stderr)
                has_error = True
        pending_writes.clear()

    # ── Provenance manifest policy (data/upstream-docs.toml) ─────────
    # --check never writes anything. On real runs: rewrite whenever any file
    # changed (--force counts, fresh timestamp); bootstrap once when missing;
    # otherwise leave untouched so git-diff gates see zero churn. Skipped on
    # incomplete fetches — a partial snapshot would be misleading provenance.
    manifest_path = root / MANIFEST_RELPATH
    if args.check:
        print("manifest: untouched (--check mode never writes)")
    elif has_error or len(fetched) != len(FILES):
        print("manifest: skipped (incomplete upstream fetch)")
    elif overall_changed or args.force:
        write_manifest(manifest_path, build_manifest_text(full_version, utc_now_iso(), fetched))
        print(f"manifest: wrote {MANIFEST_RELPATH.as_posix()} ({len(fetched)} sources)")
    elif not manifest_path.exists():
        write_manifest(manifest_path, build_manifest_text(full_version, utc_now_iso(), fetched))
        print(f"manifest: created baseline {MANIFEST_RELPATH.as_posix()} ({len(fetched)} sources)")
    else:
        print(f"manifest: up-to-date, untouched ({MANIFEST_RELPATH.as_posix()})")

    if has_error:
        return 1
    if args.check and overall_changed:
        print("Check: updates available (run without --check to apply)", file=sys.stderr)
        return 2
    if overall_changed:
        print("Sync complete: files updated. Run `python3 scripts/extract_commands.py` to regenerate commands.toml.")
    else:
        print("Sync complete: no changes.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
